apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydepl
  name: mydepl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydepl
  template:
    metadata:
      labels:
        app: mydepl
    spec:
      containers:
      - image: nginx
        name: nginx
